<Project Sdk="Meziantou.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <BlazorEnableCompression>false</BlazorEnableCompression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="1.3.2" />
    <PackageReference Include="Meziantou.Framework.CommandLine" Version="4.0.0" />
    <PackageReference Include="Meziantou.Framework.HtmlToMarkdown" Version="2.0.4" />
    <PackageReference Include="Meziantou.Framework.JsonPath" Version="3.0.1" />
    <PackageReference Include="Meziantou.Framework.Unicode" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
    <PackageReference Include="Meziantou.AspNetCore.Components" Version="3.0.4" />
    <PackageReference Include="Meziantou.Framework.ByteSize" Version="4.0.1" />
    <PackageReference Include="Meziantou.Framework.Scheduling" Version="4.0.2" />
    <PackageReference Include="Meziantou.Framework.TextDiff" Version="3.0.2" />
    <PackageReference Include="Meziantou.GitLabClient" Version="1.1.26" />
    <PackageReference Include="Meziantou.Framework.QRCode" Version="2.0.1" />
    <PackageReference Include="Meziantou.Framework.Yaml" Version="1.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Pages/RegexTester.razor.css" CssScope="b-regex" />
  </ItemGroup>

   <Target Name="CopyFiles" BeforeTargets="BeforeBuild">
    <Copy SourceFiles="wwwroot/index.html" DestinationFiles="wwwroot/404.html" />
  </Target>

</Project>
