<Project Sdk="Meziantou.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <BlazorEnableCompression>false</BlazorEnableCompression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="1.1.2" />
    <PackageReference Include="Meziantou.Framework.CommandLine" Version="3.0.8" />
    <PackageReference Include="Meziantou.Framework.HtmlToMarkdown" Version="1.0.2" />
    <PackageReference Include="Meziantou.Framework.JsonPath" Version="1.0.1" />
    <PackageReference Include="Meziantou.Framework.Unicode" Version="1.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.6" PrivateAssets="all" />
    <PackageReference Include="Meziantou.AspNetCore.Components" Version="2.0.31" />
    <PackageReference Include="Meziantou.Framework.ByteSize" Version="2.1.9" />
    <PackageReference Include="Meziantou.Framework.Scheduling" Version="2.0.11" />
    <PackageReference Include="Meziantou.Framework.TextDiff" Version="1.0.0" />
    <PackageReference Include="Meziantou.GitLabClient" Version="1.1.26" />
    <PackageReference Include="Meziantou.Framework.QRCode" Version="1.0.4" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Pages/RegexTester.razor.css" CssScope="b-regex" />
  </ItemGroup>

   <Target Name="CopyFiles" BeforeTargets="BeforeBuild">
    <Copy SourceFiles="wwwroot/index.html" DestinationFiles="wwwroot/404.html" />
  </Target>

</Project>
